"""track b intake tables

Revision ID: cb16f4415a6d
Revises: 
Create Date: 2026-09-01 21:39:31.584816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb16f4415a6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_email', sa.String(length=320), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type in ('git', 'archive')", name='ck_submission_source_type'),
    sa.CheckConstraint("status in ('queued', 'cloning', 'scoping', 'scanning', 'classifying', 'complete', 'failed')", name='ck_submission_status'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_project_id'), 'submission', ['project_id'], unique=False)
    op.create_index(op.f('ix_submission_status'), 'submission', ['status'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scanner', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('stride', sa.String(length=40), nullable=True),
    sa.Column('cis_control', sa.String(length=40), nullable=True),
    sa.CheckConstraint('submission_id is not null or source_id is not null', name='ck_finding_has_origin'),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_scanner'), 'finding', ['scanner'], unique=False)
    op.create_index(op.f('ix_finding_severity'), 'finding', ['severity'], unique=False)
    op.create_index(op.f('ix_finding_source_id'), 'finding', ['source_id'], unique=False)
    op.create_index(op.f('ix_finding_submission_id'), 'finding', ['submission_id'], unique=False)
    op.create_table('gate_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('required_controls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('project_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_stores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trust_boundaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('iac_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('questionnaire_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=100), nullable=False),
    sa.Column('answer_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_response_submission_id'), 'questionnaire_response', ['submission_id'], unique=False)
    op.create_table('risk_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('inherent_score', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overrides_fired', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_risk_assessment_tier'), 'risk_assessment', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessment_tier'), table_name='risk_assessment')
    op.drop_table('risk_assessment')
    op.drop_index(op.f('ix_questionnaire_response_submission_id'), table_name='questionnaire_response')
    op.drop_table('questionnaire_response')
    op.drop_table('project_model')
    op.drop_table('gate_decision')
    op.drop_index(op.f('ix_finding_submission_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_source_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_severity'), table_name='finding')
    op.drop_index(op.f('ix_finding_scanner'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_submission_status'), table_name='submission')
    op.drop_index(op.f('ix_submission_project_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_table('project')
    # ### end Alembic commands ###
